name: Auto Blog Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  run-blog-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install google-generativeai

      - name: Run Python script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py
